### ISSUE TITLE
Code for training generative models

### ISSUE THREAD

**Issue by ppegiosk** [annahdo/counterfactuals#1]
Thanks for sharing your code.
Could you also share a training script for the generative models ?

**Comment by annahdo** [comment]
Hi, thanks for your interest in the project and sry for the late reply. 

We did not include the training since we wanted to keep the code minimal.
However all generative models that we used are derived from existing models. We link to the respective github repo in each file. For example for [Glow](https://github.com/annahdo/counterfactuals/blob/main/counterfactuals/generative_models/flows/glow.py) we adapted code from [here](https://github.com/rosinality/glow-pytorch) where you can also find a training setup.
